# Invoke this using `docker compose up` or `podman-compose up`
version: "3.8"

services:
  dbt:
    image: "ghcr.io/dbt-labs/dbt-snowflake:${DBT_VERSION}"
    # A sample env has been provided that can be copied as .env with your own details
    env_file: ../.env
    entrypoint: ["bash", "-c", "git clone --single-branch -b $GIT_BRANCH $GIT_REPO_URL .; dbt deps; dbt build; mv ./logs/dbt.log /logs"]
    volumes:
      # Map the logs folder to our local path to optionally get the text log
      - ./:/logs
