name: pip_build
on: workflow_dispatch

env:
  # This is where the dbt-Labs image expects the project
  GITHUB_WORKSPACE: /usr/app/dbt

defaults:
  run:
    working-directory: /usr/app/dbt

jobs:
  dbt_job:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12
          cache: 'pip'
      - name: Install pip requirements
        run: pip install -U dbt-core dbt-snowflake
      - name: Run dbt
        uses: actions/checkout@v3
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          DBT_ENV_SECRET_PRIVATE_KEY: ${{ secrets.DBT_ENV_SECRET_PRIVATE_KEY }}
          DBT_PROFILES_DIR: ./docker
        run: |
          dbt deps
          dbt build
